Merge dev to main
WildCodeSchool/2023-02-JS-LaLoupe-LifeIsNotSoStrange.TM pull request #17
Opened 2023-04-21 09:49 UTC by FlorianEsn

2023-04-21 10:02 UTC, Atila18 approved these changes

2023-04-21 10:10 UTC, PhoolRiteHard approved these changes

2023-04-27 15:11 UTC, L-L-42 approved these changes

2023-04-28 07:26 UTC, Xgt72 commented on frontend/src/components/Ecran.css
You must change all the name of the classes which are not in english, "Bureau" to "desktop", and the names must be in camelCase or kebab-case.

2023-04-28 07:27 UTC, Xgt72 commented on frontend/src/components/Leaderboard.css
you must change the name of the class "tableau" to "table"(english word).

2023-04-28 07:41 UTC, Xgt72 commented on frontend/src/components/Timer.jsx
The name of the component must be the same as the filename.

2023-04-28 07:42 UTC, Xgt72 requested changes
You must change the component name Ecran to Screen and also for Ecran.css.
In Ecran.css, you must use english name for the classes.
See all the comments in different files.
At your disposal to discuss.

2023-05-05 09:29 UTC, Xgt72 commented on bash.exe.stackdump
Could you remove this file.

2023-05-05 09:29 UTC, Xgt72 commented on frontend/index.html
Please, remove the line with script window.addEventListener("load"....

2023-05-05 09:40 UTC, Xgt72 commented on frontend/src/components/Suggestion.jsx
The filename must be the same as the name of the component.

2023-05-05 09:41 UTC, Xgt72 commented on frontend/src/components/Star.jsx
The filename must be the same as the name of the component.

2023-05-05 09:45 UTC, Xgt72 commented on frontend/src/components/Contact.jsx
The filename must be the same as the name of the component or the opposite.

2023-05-05 09:46 UTC, Xgt72 requested changes
You need some change.

2023-05-09 10:05 UTC, Xgt72 approved these changes

2023-05-09 10:06 UTC, merged